[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/application",
]

[workspace.package]
edition = "2024"
rust-version = "1.99"
license = "AGPL-3.0-only"
authors = ["NDDev OpenNetwork"]

[workspace.dependencies]
nddev-device-sync-domain = { path = "crates/domain", version = "0.0.2" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
