[package]
name = "nddev-device-sync-adapters-keyring"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nddev-device-sync-application.workspace = true
keyring.workspace = true

[dev-dependencies]
nddev-device-sync-domain.workspace = true
nddev-device-sync-adapters-memory = { path = "../adapters-memory" }
